### Actually logged test
GET http://localhost:3001/api/sessions/current

### Correct Login
POST http://localhost:3001/api/sessions
Content-Type: application/json

{
  "username": "samuele",
  "password": "SamuCar02"
}

### Logout
DELETE http://localhost:3001/api/sessions/current