### Actually logged test
GET http://localhost:3001/api/sessions/current

### Correct Login
POST http://localhost:3001/api/sessions
Content-Type: application/json

{
  "username": "samuele",
  "password": "SamuCar02"
}

### Logout
DELETE http://localhost:3001/api/sessions/current

### New Game
POST http://localhost:3001/api/games

### Planning data
GET http://localhost:3001/api/games/1/planning-data

### Submitting invalid routes
POST http://localhost:3001/api/games/1/submit-route
Content-Type: application/json

{
  "routeStationIds": [1,3,4]
}

### Ranking
GET http://localhost:3001/api/ranking